repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
#  - repo: https://github.com/Bahjat/pre-commit-golang
#    rev: v1.0.1
#    run:
#      go: '1.18'
#    hooks:
#      - id: go-fmt-import
#      - id: go-vet
#      - id: go-lint
#      - id: go-unit-tests
#      - id: golangci-lint # requires github.com/golangci/golangci-lint
#        #args: [--config=.github/linters/.golangci.yml]
