# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    container_name: db_local
    restart: always #if container fails, then restart it
    environment:
      MYSQL_DATABASE: tpms_test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql

  web:
    image: golang
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_web
    ports:
      - "8080:8080"
    env_file: env/test.env
    depends_on:
      - db

volumes:
  mysql:
