# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    container_name: tmps_db_local
    restart: always #if container fails, then restart it
    environment:
      MYSQL_DATABASE: tpms
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql

  web:
    image: golang
    build: .
    container_name: tpms-be
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  mysql:

networks:
  fullstack:
    driver: bridge
