database:
  driver: "mysql"
  username: "prod_user"
  password: "AVNS_rE_h5jJrTZdY5Ki87_l"
  host: "db-mysql-tpms-do-user-12298200-0.b.db.ondigitalocean.com"
  port: "25060"
  db_name: "tpms_prod"
  ssl_mode: "REQUIRED"

cv_model_url: "localhost:8081"
