#database:
#  driver: "mysql"
#  host: "localhost:3306"
#  username: "root"
#  password: "admin"
#  db_name: "tpms_test"

cv_model_url: "localhost:8081"

database:
  driver: "mysql"
  username: "doadmin"
  password: "AVNS_y4FdaN8ad-tDuieQhuP"
  host: "db-mysql-tpms-do-user-12298200-0.b.db.ondigitalocean.com"
  port: "25060"
  db_name: "tpms_test"
  ssl_mode: "REQUIRED"
